blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/raufA1/HelmStack/discussions
    about: Ask questions and discuss HelmStack with the community
  - name: 📖 Documentation
    url: https://github.com/raufA1/HelmStack/blob/main/README.md
    about: Read the documentation and command reference
  - name: 🚀 Quick Start Guide
    url: https://github.com/raufA1/HelmStack/blob/main/README.md#-quick-start
    about: Get started with HelmStack in minutes
