#!/usr/bin/env bash
set -e
NAME="$1"; DESC="$2"; DOCS_DIR="$3"; INCOMING_DIR="$4"; PLANS_DIR="$5"
mkdir -p "$DOCS_DIR" "$INCOMING_DIR" "$PLANS_DIR"
if [ ! -f README.md ]; then
cat > README.md <<EOF
# ${NAME}

${DESC}

Generated by HelmStack.
See \`${PLANS_DIR}\` for planning artifacts.
EOF
fi
if [ ! -f "${PLANS_DIR}/STATUS.md" ]; then
cat > "${PLANS_DIR}/STATUS.md" <<'EOF'
# STATUS
- Project initialized.
- Run `make fix` to generate or refresh the plan.
EOF
fi
echo "✅ Smart start ready. Docs root: ${DOCS_DIR}"